### ISSUE TITLE
Reporting a problem with something in this repo 

### ISSUE THREAD

**Issue by AmandaBrackett** [aosmith16/practice-repo#14]
I am describing the problem I found here. I am succinct but as clear as I can be in the text. 

``` r
library(ggplot2)
ggplot(data = mtcars[2:3,], aes(x = factor(gear), y = mpg)) +
    geom_point(aes(color = factor(vs)), 
               position = position_dodge(width = .5),
               size = 2) +
    geom_errorbar(aes(ymin = mpg - 1, ymax = mpg + 1),
                  position = position_dodge(width = .5),
                  width = .2)
```

![](https://i.imgur.com/10VmeIB.png)

<sup>Created on 2021-06-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by aosmith16** [comment]
I am still impressed by how easy reprex makes it to include plots. I'm closing this issue so you can see what kind of notifications you get.
